language: python
before_install:
  - openssl aes-256-cbc -K $encrypted_8212be8fbd76_key -iv $encrypted_8212be8fbd76_iv -in publish-key.enc -out publish-key -d
  - chmod u=rw,og= ~/.ssh/publish-key
  - echo "Host github.com" >> ~/.ssh/config
  - echo "  IdentityFile ~/.ssh/publish-key" >> ~/.ssh/config
  
  # substitua git@github.com:humrochagf/humrochagf.github.io.git
  # pelo endereço de acesso ssh do seu repositório
  - git remote set-url origin git@github.com:humrochagf/humrochagf.github.io.git
  
  # Caso esteja montando a página de projeto troque master:master
  # por gh-pages:gh-pages
  - git fetch origin -f master:master
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
script:
  - make github